auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  # 允许远程推送
  grpc_server_max_recv_msg_size: 104857600  # 100MB
  grpc_server_max_send_msg_size: 104857600  # 100MB
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# 针对TEE项目的特殊配置
limits_config:
  # 增加日志摄入限制以处理高频日志和多节点
  ingestion_rate_mb: 64  # 增加到64MB以支持多节点
  ingestion_burst_size_mb: 128  # 增加突发限制
  per_stream_rate_limit: 32MB  # 增加每流限制
  per_stream_rate_limit_burst: 64MB
  max_streams_per_user: 50000  # 增加流数量支持更多节点
  max_line_size: 512000  # 增加行大小限制
  
  # 查询限制
  max_query_length: 721h
  max_query_parallelism: 64  # 增加并行查询数
  max_entries_limit_per_query: 10000  # 增加查询结果限制
  
  # 保留策略
  retention_period: 168h  # 7天
  
  # 多租户支持（支持多节点）
  max_concurrent_tail_requests: 100
  max_global_streams_per_user: 50000

# 压缩配置
compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem

# 针对TEE日志的优化
frontend:
  max_outstanding_per_tenant: 256
  compress_responses: true

querier:
  max_concurrent: 20 